-- CreateTable
CREATE TABLE "Player" (
    "id" SERIAL NOT NULL,
    "localID" TEXT,
    "teamName" TEXT,
    "firstName" TEXT,
    "lastName" TEXT,
    "primaryPosition" TEXT,
    "pitcherRole" TEXT,
    "power" TEXT,
    "contact" TEXT,
    "speed" TEXT,
    "fielding" TEXT,
    "arm" TEXT,
    "velocity" TEXT,
    "junk" TEXT,
    "accuracy" TEXT,
    "age" TEXT,
    "trait" TEXT,
    "subType" TEXT,
    "league" TEXT,
    "gender" TEXT,
    "throws" TEXT,
    "bats" TEXT,
    "secondaryPosition" TEXT,
    "rating" TEXT,
    "trait1" TEXT,
    "chemistry1" TEXT,
    "trait2" TEXT,
    "chemistry2" TEXT,
    "careerStart" TEXT,
    "careerEnd" TEXT,
    "fourSeamFastball" TEXT,
    "twoSeamFastball" TEXT,
    "screwball" TEXT,
    "changeup" TEXT,
    "forkball" TEXT,
    "curveball" TEXT,
    "slider" TEXT,
    "cutFastball" TEXT,
    "windup" TEXT,
    "pitchAngle" TEXT,

    CONSTRAINT "Player_pkey" PRIMARY KEY ("id")
);
