export const BASE_URL = "http://localhost:5005";

export const SKILLS = {
  arsenal: "arsenal",
  fullName: "fullName",
  team: "team",
  bats: "bats",
  throws: "throws",
  gender: "gender",
  primaryPosition: "primaryPosition",
  primaryPositionShort: "primaryPositionShort",
  secondaryPosition: "secondaryPosition",
  secondaryPositionShort: "secondaryPositionShort",
  pitcherRole: "pitcherRole",
  pitcherRoleShort: "pitcherRoleShort",
  league: "league",
  trait1: "trait1",
  trait2: "trait2",
  localID: "localID",
  teamId: "teamId",
  leagueId: "leagueId",
  firstName: "firstName",
  lastName: "lastName",
  power: "power",
  contact: "contact",
  speed: "speed",
  rating: "rating",
  fielding: "fielding",
  arm: "arm",
  velocity: "velocity",
  junk: "junk",
  accuracy: "accuracy",
  age: "age",
  jerseyNumber: "jerseyNumber",
  traitId1: "traitId1",
  traitId2: "traitId2",
  careerStart: "careerStart",
  careerEnd: "careerEnd",
  windup: "windup",
  pitchAngle: "pitchAngle",
  playerChemistry: "playerChemistry",
  salary: "salary",
};

// also used for the listed table headers
export const PLAYER_ATTRIBUTES: string[] = [
  SKILLS.team,
  SKILLS.league,
  SKILLS.fullName,
  SKILLS.primaryPositionShort,
  SKILLS.secondaryPositionShort,
  SKILLS.power,
  SKILLS.contact,
  SKILLS.speed,
  SKILLS.fielding,
  SKILLS.arm,
  SKILLS.bats,
  SKILLS.throws,
  SKILLS.age,
  SKILLS.pitcherRoleShort,
  SKILLS.velocity,
  SKILLS.junk,
  SKILLS.accuracy,
  SKILLS.playerChemistry,
  SKILLS.trait1,
  SKILLS.trait2,
];

// for columns with abbreviated (short) names
export const playerColumnSort = {
  [SKILLS.fullName]: SKILLS.firstName,
  [SKILLS.primaryPositionShort]: SKILLS.primaryPosition,
  [SKILLS.secondaryPositionShort]: SKILLS.secondaryPosition,
  [SKILLS.pitcherRoleShort]: SKILLS.pitcherRole,
  [SKILLS.team]: SKILLS.teamId,
  [SKILLS.league]: SKILLS.leagueId,
  [SKILLS.trait1]: SKILLS.traitId1,
  [SKILLS.trait2]: SKILLS.traitId2,
};

export const PITCH_TYPE = {
  fourSeamFastball: { short: "4F", full: "4-seam fastball" },
  twoSeamFastball: { short: "2F", full: "2-seam fastball" },
  cutFastball: { short: "CF", full: "Cut fastball" },
  curveball: { short: "CB", full: "Curveball" },
  slider: { short: "SL", full: "Slider" },
  screwball: { short: "SB", full: "Screwball" },
  changeup: { short: "CH", full: "Change up" },
  forkball: { short: "FK", full: "Forkball" },
};

export const tableHeaders: { [key: string]: string } = {
  [SKILLS.team]: "team",
  [SKILLS.fullName]: "name",
  [SKILLS.primaryPositionShort]: "pos",
  [SKILLS.secondaryPositionShort]: "pos2",
  [SKILLS.rating]: "rating",
  [SKILLS.power]: "pow",
  [SKILLS.contact]: "con",
  [SKILLS.speed]: "spd",
  [SKILLS.fielding]: "fld",
  [SKILLS.arm]: "arm",
  [SKILLS.bats]: "bat",
  [SKILLS.throws]: "thr",
  [SKILLS.age]: "age",
  [SKILLS.pitcherRoleShort]: "pitch",
  [SKILLS.arsenal]: "arsenal",
  [SKILLS.velocity]: "vel",
  [SKILLS.junk]: "jnk",
  [SKILLS.accuracy]: "acc",
  [SKILLS.trait1]: "trait",
  [SKILLS.trait2]: "trait 2",
  [SKILLS.jerseyNumber]: "#",
  [SKILLS.playerChemistry]: "chem",
  [SKILLS.careerStart]: "strt",
  [SKILLS.salary]: "$",
};
