# PRODUCTION!!!!!!!!!!!!!!
version: "3.9"
services:
  api:
    restart: always
    stdin_open: true
    build: ./server
    environment:
      - DATABASE_URL=postgresql://root:password@postgresDb:5432/mydb?schema=public
    volumes:
      - ./server:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 5005:5005
    depends_on:
      - postgresDb

  postgresDb:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_DB=mydb
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password
    ports:
      - 5432:5432
    volumes:
      - postgresDb:/var/lib/postgresql/data

  client:
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    build: ./client
    volumes:
      - /app/node_modules
      - ./client:/app

  nginx:
    depends_on:
      - api
      - client
    restart: always
    build:
      context: ./nginx
      target: "prod"
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./etc/nginx/templates:/etc/nginx/templates:ro
      - ./etc/letsencrypt:/etc/letsencrypt:ro

  certbot:
    container_name: certbot
    image: certbot/certbot:latest
    depends_on:
      - nginx
    command: >-
      certonly --reinstall --webroot --webroot-path=/var/www/certbot
      --email admin@reallyepichardball.com --agree-tos --no-eff-email
      -d reallyepichardball.com
    volumes:
      - ./etc/letsencrypt:/etc/letsencrypt
      - ./certbot/data:/var/www/certbot

volumes:
  postgresDb:
    driver: local
