const sharedSelect = {
  id: true,
  localID: true,
  firstName: true,
  lastName: true,
  age: true,
  gender: true,
  throws: true,
  power: true,
  contact: true,
  speed: true,
  fielding: true,
  jerseyNumber: true,
  careerStart: true,
  careerEnd: true,
  playerChemistry: true,
  salary: true,
  team: true,
  teamSlug: true,
  league: true,
  trait1: true,
  traitChemistry1: true,
  trait2: true,
  traitChemistry2: true,
};

const playerSelect = {
  ...sharedSelect,
  primaryPosition: true,
  arm: true,
  age: true,
  gender: true,
  throws: true,
  bats: true,
  secondaryPosition: true,
  jerseyNumber: true,
};

const pitcherSelect = {
  ...sharedSelect,
  pitcherRole: true,
  velocity: true,
  junk: true,
  accuracy: true,
  fourSeamFastball: true,
  twoSeamFastball: true,
  screwball: true,
  changeup: true,
  forkball: true,
  curveball: true,
  slider: true,
  cutFastball: true,
  windup: true,
  pitchAngle: true,
};

module.exports = { playerSelect, pitcherSelect };
