const playerSelect = {
  firstName: true,
  lastName: true,
  primaryPosition: true,
  pitcherRole: true,
  power: true,
  contact: true,
  speed: true,
  fielding: true,
  arm: true,
  velocity: true,
  junk: true,
  accuracy: true,
  age: true,
  gender: true,
  throws: true,
  bats: true,
  secondaryPosition: true,
  jerseyNumber: true,
  careerStart: true,
  careerEnd: true,
  fourSeamFastball: true,
  twoSeamFastball: true,
  screwball: true,
  changeup: true,
  forkball: true,
  curveball: true,
  slider: true,
  cutFastball: true,
  windup: true,
  pitchAngle: true,
  playerChemistry: true,
  salary: true,
  team: { select: { name: true } },
  league: { select: { name: true } },
  trait1: { select: { type: true, chemistry: true } },
  trait2: { select: { type: true, chemistry: true } },
};

module.exports = { playerSelect };
